//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Savonia.Measurements.Clients.Service20
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeasurementModel", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class MeasurementModel : object
    {
        
        private Savonia.Measurements.Clients.Service20.DataModel[] DataField;
        
        private Savonia.Measurements.Clients.Service20.Location LocationField;
        
        private string NoteField;
        
        private string ObjectField;
        
        private string TagField;
        
        private System.DateTimeOffset TimestampField;
        
        private string TimestampISO8601Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Savonia.Measurements.Clients.Service20.DataModel[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Savonia.Measurements.Clients.Service20.Location Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note
        {
            get
            {
                return this.NoteField;
            }
            set
            {
                this.NoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Object
        {
            get
            {
                return this.ObjectField;
            }
            set
            {
                this.ObjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimestampISO8601
        {
            get
            {
                return this.TimestampISO8601Field;
            }
            set
            {
                this.TimestampISO8601Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class Location : object
    {
        
        private System.Nullable<double> LatitudeField;
        
        private System.Nullable<double> LongitudeField;
        
        private string WellKnownTextWGS84Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WellKnownTextWGS84
        {
            get
            {
                return this.WellKnownTextWGS84Field;
            }
            set
            {
                this.WellKnownTextWGS84Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataModel", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class DataModel : object
    {
        
        private byte[] BinaryValueField;
        
        private string BinaryValueBase64Field;
        
        private System.Nullable<long> LongValueField;
        
        private string TagField;
        
        private string TextValueField;
        
        private System.Nullable<double> ValueField;
        
        private string XmlValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BinaryValue
        {
            get
            {
                return this.BinaryValueField;
            }
            set
            {
                this.BinaryValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaryValueBase64
        {
            get
            {
                return this.BinaryValueBase64Field;
            }
            set
            {
                this.BinaryValueBase64Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> LongValue
        {
            get
            {
                return this.LongValueField;
            }
            set
            {
                this.LongValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextValue
        {
            get
            {
                return this.TextValueField;
            }
            set
            {
                this.TextValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlValue
        {
            get
            {
                return this.XmlValueField;
            }
            set
            {
                this.XmlValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveResult", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class SaveResult : object
    {
        
        private Savonia.Measurements.Clients.Service20.Failure[] FailuresField;
        
        private Savonia.Measurements.Clients.Service20.MeasurementStatus[] StatusesField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Savonia.Measurements.Clients.Service20.Failure[] Failures
        {
            get
            {
                return this.FailuresField;
            }
            set
            {
                this.FailuresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Savonia.Measurements.Clients.Service20.MeasurementStatus[] Statuses
        {
            get
            {
                return this.StatusesField;
            }
            set
            {
                this.StatusesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Failure", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class Failure : object
    {
        
        private int CodeField;
        
        private int IndexField;
        
        private string ReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Index
        {
            get
            {
                return this.IndexField;
            }
            set
            {
                this.IndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeasurementStatus", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class MeasurementStatus : object
    {
        
        private bool IsSavedField;
        
        private System.DateTimeOffset MeasurementTimeStampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSaved
        {
            get
            {
                return this.IsSavedField;
            }
            set
            {
                this.IsSavedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTimeOffset MeasurementTimeStamp
        {
            get
            {
                return this.MeasurementTimeStampField;
            }
            set
            {
                this.MeasurementTimeStampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeasurementPackage", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class MeasurementPackage : object
    {
        
        private string KeyField;
        
        private Savonia.Measurements.Clients.Service20.MeasurementModel[] MeasurementsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Savonia.Measurements.Clients.Service20.MeasurementModel[] Measurements
        {
            get
            {
                return this.MeasurementsField;
            }
            set
            {
                this.MeasurementsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeasurementQueryModel", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class MeasurementQueryModel : object
    {
        
        private Savonia.Measurements.Clients.Service20.BinaryDataFormat BinaryValueFormatField;
        
        private System.Nullable<System.DateTimeOffset> FromField;
        
        private int IDField;
        
        private bool InclusiveFromField;
        
        private bool InclusiveToField;
        
        private string KeyField;
        
        private string NameField;
        
        private string ObjField;
        
        private string SensorsField;
        
        private string TagField;
        
        private System.Nullable<int> TakeField;
        
        private System.Nullable<System.DateTimeOffset> ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Savonia.Measurements.Clients.Service20.BinaryDataFormat BinaryValueFormat
        {
            get
            {
                return this.BinaryValueFormatField;
            }
            set
            {
                this.BinaryValueFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTimeOffset> From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InclusiveFrom
        {
            get
            {
                return this.InclusiveFromField;
            }
            set
            {
                this.InclusiveFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InclusiveTo
        {
            get
            {
                return this.InclusiveToField;
            }
            set
            {
                this.InclusiveToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obj
        {
            get
            {
                return this.ObjField;
            }
            set
            {
                this.ObjField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sensors
        {
            get
            {
                return this.SensorsField;
            }
            set
            {
                this.SensorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Take
        {
            get
            {
                return this.TakeField;
            }
            set
            {
                this.TakeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTimeOffset> To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BinaryDataFormat", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public enum BinaryDataFormat : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ByteArray = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Base64String = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaPackage", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class MetaPackage : object
    {
        
        private string KeyField;
        
        private Savonia.Measurements.Clients.Service20.MetaModel[] MetaDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Savonia.Measurements.Clients.Service20.MetaModel[] MetaData
        {
            get
            {
                return this.MetaDataField;
            }
            set
            {
                this.MetaDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaModel", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class MetaModel : object
    {
        
        private byte[] BinaryValueField;
        
        private string BinaryValueBase64Field;
        
        private string ObjectField;
        
        private string TagField;
        
        private System.Nullable<int> VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BinaryValue
        {
            get
            {
                return this.BinaryValueField;
            }
            set
            {
                this.BinaryValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BinaryValueBase64
        {
            get
            {
                return this.BinaryValueBase64Field;
            }
            set
            {
                this.BinaryValueBase64Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Object
        {
            get
            {
                return this.ObjectField;
            }
            set
            {
                this.ObjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MetaQueryModel", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class MetaQueryModel : object
    {
        
        private Savonia.Measurements.Clients.Service20.BinaryDataFormat BinaryValueFormatField;
        
        private string KeyField;
        
        private string ObjField;
        
        private string TagField;
        
        private System.Nullable<int> VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Savonia.Measurements.Clients.Service20.BinaryDataFormat BinaryValueFormat
        {
            get
            {
                return this.BinaryValueFormatField;
            }
            set
            {
                this.BinaryValueFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obj
        {
            get
            {
                return this.ObjField;
            }
            set
            {
                this.ObjField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SensorModel", Namespace="http://schemas.datacontract.org/2004/07/Savonia.Measurements.Models")]
    public partial class SensorModel : object
    {
        
        private string DescriptionField;
        
        private Savonia.Measurements.Clients.Service20.Location LocationField;
        
        private string NameField;
        
        private string TagField;
        
        private string UnitField;
        
        private System.Nullable<int> ValueDecimalCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Savonia.Measurements.Clients.Service20.Location Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag
        {
            get
            {
                return this.TagField;
            }
            set
            {
                this.TagField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit
        {
            get
            {
                return this.UnitField;
            }
            set
            {
                this.UnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ValueDecimalCount
        {
            get
            {
                return this.ValueDecimalCountField;
            }
            set
            {
                this.ValueDecimalCountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Savonia.MeasurementService.V3", ConfigurationName="Savonia.Measurements.Clients.Service20.IMeasurementsService")]
    public interface IMeasurementsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="Savonia.MeasurementService.V3/IMeasurementsService/SaveMeasurements", ReplyAction="Savonia.MeasurementService.V3/IMeasurementsService/SaveMeasurementsResponse")]
        System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.SaveResult> SaveMeasurementsAsync(string key, Savonia.Measurements.Clients.Service20.MeasurementModel[] measurements);
        
        [System.ServiceModel.OperationContractAttribute(Action="Savonia.MeasurementService.V3/IMeasurementsService/SaveMeasurementPackage", ReplyAction="Savonia.MeasurementService.V3/IMeasurementsService/SaveMeasurementPackageResponse" +
            "")]
        System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.SaveResult> SaveMeasurementPackageAsync(Savonia.Measurements.Clients.Service20.MeasurementPackage measurementPackage);
        
        [System.ServiceModel.OperationContractAttribute(Action="Savonia.MeasurementService.V3/IMeasurementsService/RestGetMeasurements", ReplyAction="Savonia.MeasurementService.V3/IMeasurementsService/RestGetMeasurementsResponse")]
        System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MeasurementModel[]> RestGetMeasurementsAsync(string key, string sensors, string obj, string tag, string take, string from, string to, string inclusiveFrom, string inclusiveTo, string binaryValueFormat);
        
        [System.ServiceModel.OperationContractAttribute(Action="Savonia.MeasurementService.V3/IMeasurementsService/GetMeasurements", ReplyAction="Savonia.MeasurementService.V3/IMeasurementsService/GetMeasurementsResponse")]
        System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MeasurementModel[]> GetMeasurementsAsync(Savonia.Measurements.Clients.Service20.MeasurementQueryModel query);
        
        [System.ServiceModel.OperationContractAttribute(Action="Savonia.MeasurementService.V3/IMeasurementsService/SaveMetaPackage", ReplyAction="Savonia.MeasurementService.V3/IMeasurementsService/SaveMetaPackageResponse")]
        System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.SaveResult> SaveMetaPackageAsync(Savonia.Measurements.Clients.Service20.MetaPackage metaPackage);
        
        [System.ServiceModel.OperationContractAttribute(Action="Savonia.MeasurementService.V3/IMeasurementsService/SaveMeta", ReplyAction="Savonia.MeasurementService.V3/IMeasurementsService/SaveMetaResponse")]
        System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.SaveResult> SaveMetaAsync(string key, Savonia.Measurements.Clients.Service20.MetaModel[] meta);
        
        [System.ServiceModel.OperationContractAttribute(Action="Savonia.MeasurementService.V3/IMeasurementsService/RestGetMeta", ReplyAction="Savonia.MeasurementService.V3/IMeasurementsService/RestGetMetaResponse")]
        System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MetaModel[]> RestGetMetaAsync(string key, string obj, string tag, string version, string binaryValueFormat);
        
        [System.ServiceModel.OperationContractAttribute(Action="Savonia.MeasurementService.V3/IMeasurementsService/GetMeta", ReplyAction="Savonia.MeasurementService.V3/IMeasurementsService/GetMetaResponse")]
        System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MetaModel[]> GetMetaAsync(Savonia.Measurements.Clients.Service20.MetaQueryModel query);
        
        [System.ServiceModel.OperationContractAttribute(Action="Savonia.MeasurementService.V3/IMeasurementsService/GetSensors", ReplyAction="Savonia.MeasurementService.V3/IMeasurementsService/GetSensorsResponse")]
        System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.SensorModel[]> GetSensorsAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="Savonia.MeasurementService.V3/IMeasurementsService/GetSaveMeasurementsTemplate", ReplyAction="Savonia.MeasurementService.V3/IMeasurementsService/GetSaveMeasurementsTemplateRes" +
            "ponse")]
        System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MeasurementModel[]> GetSaveMeasurementsTemplateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="Savonia.MeasurementService.V3/IMeasurementsService/GetSaveMeasurementPackageTempl" +
            "ate", ReplyAction="Savonia.MeasurementService.V3/IMeasurementsService/GetSaveMeasurementPackageTempl" +
            "ateResponse")]
        System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MeasurementPackage> GetSaveMeasurementPackageTemplateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IMeasurementsServiceChannel : Savonia.Measurements.Clients.Service20.IMeasurementsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class MeasurementsServiceClient : System.ServiceModel.ClientBase<Savonia.Measurements.Clients.Service20.IMeasurementsService>, Savonia.Measurements.Clients.Service20.IMeasurementsService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MeasurementsServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MeasurementsServiceClient.GetBindingForEndpoint(endpointConfiguration), MeasurementsServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MeasurementsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MeasurementsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MeasurementsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MeasurementsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MeasurementsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.SaveResult> SaveMeasurementsAsync(string key, Savonia.Measurements.Clients.Service20.MeasurementModel[] measurements)
        {
            return base.Channel.SaveMeasurementsAsync(key, measurements);
        }
        
        public System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.SaveResult> SaveMeasurementPackageAsync(Savonia.Measurements.Clients.Service20.MeasurementPackage measurementPackage)
        {
            return base.Channel.SaveMeasurementPackageAsync(measurementPackage);
        }
        
        public System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MeasurementModel[]> RestGetMeasurementsAsync(string key, string sensors, string obj, string tag, string take, string from, string to, string inclusiveFrom, string inclusiveTo, string binaryValueFormat)
        {
            return base.Channel.RestGetMeasurementsAsync(key, sensors, obj, tag, take, from, to, inclusiveFrom, inclusiveTo, binaryValueFormat);
        }
        
        public System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MeasurementModel[]> GetMeasurementsAsync(Savonia.Measurements.Clients.Service20.MeasurementQueryModel query)
        {
            return base.Channel.GetMeasurementsAsync(query);
        }
        
        public System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.SaveResult> SaveMetaPackageAsync(Savonia.Measurements.Clients.Service20.MetaPackage metaPackage)
        {
            return base.Channel.SaveMetaPackageAsync(metaPackage);
        }
        
        public System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.SaveResult> SaveMetaAsync(string key, Savonia.Measurements.Clients.Service20.MetaModel[] meta)
        {
            return base.Channel.SaveMetaAsync(key, meta);
        }
        
        public System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MetaModel[]> RestGetMetaAsync(string key, string obj, string tag, string version, string binaryValueFormat)
        {
            return base.Channel.RestGetMetaAsync(key, obj, tag, version, binaryValueFormat);
        }
        
        public System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MetaModel[]> GetMetaAsync(Savonia.Measurements.Clients.Service20.MetaQueryModel query)
        {
            return base.Channel.GetMetaAsync(query);
        }
        
        public System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.SensorModel[]> GetSensorsAsync(string key)
        {
            return base.Channel.GetSensorsAsync(key);
        }
        
        public System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MeasurementModel[]> GetSaveMeasurementsTemplateAsync()
        {
            return base.Channel.GetSaveMeasurementsTemplateAsync();
        }
        
        public System.Threading.Tasks.Task<Savonia.Measurements.Clients.Service20.MeasurementPackage> GetSaveMeasurementPackageTemplateAsync()
        {
            return base.Channel.GetSaveMeasurementPackageTemplateAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IMeasurementsService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMeasurementsService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IMeasurementsService))
            {
                return new System.ServiceModel.EndpointAddress("https://sami.savonia.fi/Service/2.0/MeasurementsService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMeasurementsService))
            {
                return new System.ServiceModel.EndpointAddress("https://sami.savonia.fi/Service/2.0/MeasurementsService.svc/basic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IMeasurementsService,
            
            BasicHttpBinding_IMeasurementsService,
        }
    }
}
